"""baseline schema

Revision ID: c1020c8fd9ac
Revises: 
Create Date: 2026-07-26 22:28:43.639949
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c1020c8fd9ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'country', name='uq_city_name_country')
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cities_name'), ['name'], unique=False)

    op.create_table('reel_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('canonical_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('author_handle', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reel_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reel_sources_canonical_id'), ['canonical_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('apple_sub', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('reels_this_month', sa.Integer(), nullable=False),
    sa.Column('quota_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_apple_sub'), ['apple_sub'], unique=True)

    op.create_table('collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'city_id', 'category', name='uq_collection_scope')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_user_id'), ['user_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('apns_token', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apns_token')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('places',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_place_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('cuisine', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('location_source', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('hours', sa.JSON(), nullable=True),
    sa.Column('utc_offset_minutes', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('business_status', sa.String(), nullable=True),
    sa.Column('google_maps_url', sa.String(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_places_external_place_id'), ['external_place_id'], unique=False)

    op.create_table('user_reels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('reel_source_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reel_source_id'], ['reel_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'reel_source_id', name='uq_user_reel')
    )
    with op.batch_alter_table('user_reels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_reels_reel_source_id'), ['reel_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_reels_user_id'), ['user_id'], unique=False)

    op.create_table('user_places',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('place_id', sa.String(), nullable=False),
    sa.Column('reel_source_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tips', sa.JSON(), nullable=True),
    sa.Column('what_to_order', sa.JSON(), nullable=True),
    sa.Column('vibe', sa.JSON(), nullable=True),
    sa.Column('instagram_handle', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('hours_hint', sa.String(), nullable=True),
    sa.Column('price_level_ai', sa.Integer(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('user_notes', sa.String(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['reel_source_id'], ['reel_sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'place_id', 'reel_source_id', name='uq_user_place_reel')
    )
    with op.batch_alter_table('user_places', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_places_place_id'), ['place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_places_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_places_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_places_place_id'))

    op.drop_table('user_places')
    with op.batch_alter_table('user_reels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reels_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_reels_reel_source_id'))

    op.drop_table('user_reels')
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_places_external_place_id'))

    op.drop_table('places')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))

    op.drop_table('devices')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_user_id'))

    op.drop_table('collections')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_apple_sub'))

    op.drop_table('users')
    with op.batch_alter_table('reel_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reel_sources_canonical_id'))

    op.drop_table('reel_sources')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_name'))

    op.drop_table('cities')
    # ### end Alembic commands ###
